theme: jekyll-theme-minimal

title: Daniyal Akbar
description: I am a passionate IoT enthusiast.

# Optional â€“ add this later if you have a profile image
# logo: /assets/img/profile.jpg

# Optional social links (used by some themes/plugins)
linkedin_username: daniyalakbar